version: '3'

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: books
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - webnet
    api:
        restart: always
        ports:
            - "3000:3000"
        build:
            dockerfile: Dockerfile
            context: .
        environment:
            MYSQL_HOST: db
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: books
            PORT: 3000
        command: node src/server.js
        depends_on:
            - db
        volumes:
            - .:/home/node/app
        networks:
            - webnet
networks:
    webnet:

volumes:
    db_data: {}
